spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432
#    username: postgres
#    password: 1234
#  jpa:
#   hibernate: ddl-auto=create
#   show-sql: true
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true




server:
  port: 8081